server:
  port: 8080

spring:
  mail:
    username: sergioandresrr@ufps.edu.co
    password: hcnrhfusxwvhgzjt
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/innova?serverTimezone=UTC
    username: root
    password: secret
    hikari:
      maxLifeTime: 600000
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
